---

# Important Notes:
# 1. The config under `/products/<PRODUCT_ALIAS>` must be compatible with `download-product` config file.
#    Ref: http://docs.pivotal.io/platform-automation/v3.0/reference/inputs-outputs.html#download-product-config
# 2. For OpsMan, we must not set `stemcell-iaas` while all others must set it with the right value
# 3. The options available for `stemcell-iaas`: vsphere; vcloud; openstack; google; azure; aws

products:

  # ==== Ops Manager
  opsman:
    product-version: "2.7.7"
    pivnet-product-slug: ops-manager
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*gcp*.yml"

  # ==== Products

  # PKS
  pks:
    product-version: "1.6.0"
    pivnet-product-slug: pivotal-container-service
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "pivotal-container-service-*.pivotal" 
    stemcell-iaas: google

  # PAS
  pas:
    product-version: "2.5.15"
    pivnet-product-slug: elastic-runtime
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "srt-*.pivotal"   # For full fledged PAS, use "cf-*.pivotal"
    stemcell-iaas: google

  sso: 
    product-version: "1.10.1"
    pivnet-product-slug: pivotal_single_sign-on_service
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "Pivotal_Single_Sign-On_Service*.pivotal"
    stemcell-iaas: google
